### ISSUE TITLE
Feature Request: Move apps to UMA0

### ISSUE THREAD

**Issue by wmxp** [ONElua/AppManager-Plus#3]
There are now multiple different external storage options available on the Vita, which all have the ability to make use of storage mounted as UMA0:

1) Using external USB storage on PSTV via VitaShell; or by using the usbmc TaiHen driver.
https://github.com/yifanlu/usbmc

2) psvsd hardware mod for 3G Vita, also using the usbmc driver
http://psvsd.henkaku.xyz/

3) gamesd modified driver for the SD2Vita project. Mounts gamecardSD as UMA0
https://www.reddit.com/r/vitahacks/comments/6mrzqm/use_your_gamecardsdcard_as_external_storage/
https://github.com/SonryP/gamecard-microsd

4) gamesd modified driver for the SD2Vita project. Mounts gamecardSD as UX0 & Vita memcard as UMA0
https://www.reddit.com/r/vitahacks/comments/6n3sox/added_uma0_for_vita_memory_card/

Can AppManager Plus be updated to assist with this functionality?

**Comment by ONElua** [comment]
move apps to uma0 ??? or update explorer with uma0 ???
