### ISSUE TITLE
save problem and  (C2-11807-7).

### ISSUE THREAD

**Issue by meysam25** [ONElua/AppManager-Plus#4]
i have sd card as ux0 and vita card as uma0
when i tranfser game from ux0 to uma0 i have this error  (C2-11807-7). 
or even when i dont have this error i got save file not found error .
plz tell me what to do

**Comment by meysam25** [comment]
no one answer to this question :( i dont belivet

**Comment by ONElua** [comment]
well if you have the sd mounted as ux0 and transfer a game to uma0 (sony MC) on some cases the games wont boot at all, and when they do you'll get the savedata not found error, thats normal, and I think we mentioned it on the readme file :)
